### ISSUE TITLE
Bidirectional traffic unable to pass with DSA support 

### ISSUE THREAD

**Issue by semihalf-wojtas-marcin** [Semihalf/marvell-dpdk#13]
Push traffic with pktgen unidirectionally - when done for the first time, direction does not matter. Stop transfer and enable 'reverse' direction - no packet will pass.

**Comment by semihalf-ostruszka-andrzej** [comment]
This turned out to be combination of our pktgen setup and feature of switch.  We were using two ports on pktgen with MAC addresses pointing to each other and on the first packet in the other direction switch learned the MACs and stopped forwarding to the CPU port and was forwarding on its own.
